on: [push, pull_request]
name: Golang Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.0]
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: go test ./...

